# Generated by Django 6.0.1 on 2026-01-23 04:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0003_alter_order_order_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderitems",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to="cart.order",
            ),
        ),
    ]
